### ISSUE TITLE
how to use regularized matching in this extension

### ISSUE THREAD

**Issue by name555difficult** [Future-Scholars/paperlib-format-pubname-extension#1]
When I use this extension to transform the conference name to pubname. The following situation will occur:

```Json
"The Thirty-eighth Annual Conference on Neural Information Processing Systems": "NeurIPS"
"The xxxx Annual Conference on Neural Information Processing Systems": "NeurIPS"
"European Conference on Computer Vision": "ECCV",
"European Conference on Computer Vision (ECCV)": "ECCV"
```

I need to set a key-value pair for each case. So can we use a form similar to regularized matching?

Sincerely thank you for answering my question?

**Comment by GeoffreyChen777** [comment]
1. Disable the `Exact match` option.
2. Use a minimal string to match. For example, 
```
For these two cases,

"European Conference on Computer Vision": "ECCV",
"European Conference on Computer Vision (ECCV)": "ECCV"

->

You only need one

"European Conference on Computer Vision": "ECCV",
```
If the publication name contains `European Conference on Computer Vision`, it will be replaced by `ECCV`.

**Comment by name555difficult** [comment]
OK, thank you for your detailed answer. I have solved this problem according to your suggestion. Once again I would like to express my sincere thanks to you
